import { Home } from "lucide-react";
import type { WorkoutDay } from "./workout-data";

export const HOME_WORKOUTS: WorkoutDay[] = [
  {
    id: "home-pull",
    name: "Pull & Hang",
    icon: Home,
    day: "home",
    focus: "Grip & Lats",
    color: "hsl(213 80% 58%)",
    exercises: [
      {
        id: "lib-6",
        name: "Pull-ups",
        sets: 3,
        reps: "Max",
        targetMuscle: "Lats/Biceps",
        trackWeight: false,
        notes: "Full dead hang start, chin over bar — log reps only",
      },
      {
        id: "home-2",
        name: "Dead Hang",
        sets: 3,
        reps: "30-60",
        targetMuscle: "Grip",
        trackWeight: false,
        repLabel: "Sec",
        notes: "Relax shoulders, hang for time — build toward 60s",
      },
      {
        id: "home-3",
        name: "Towel Hang",
        sets: 3,
        reps: "20-30",
        targetMuscle: "Grip",
        trackWeight: false,
        repLabel: "Sec",
        notes: "Drape towel over bar, double overhand — harder than it looks",
      },
    ],
  },
  {
    id: "home-abs",
    name: "Abs",
    icon: Home,
    day: "home",
    focus: "Core",
    color: "hsl(38 90% 52%)",
    exercises: [
      {
        id: "home-4",
        name: "Ab Wheel Rollouts",
        sets: 3,
        reps: "10-15",
        targetMuscle: "Abs",
        trackWeight: false,
        notes: "Slow rollout to full extension, squeeze back — don't let hips sag",
      },
      {
        id: "home-7",
        name: "Hanging Knee Raises",
        sets: 3,
        reps: "12-15",
        targetMuscle: "Abs",
        trackWeight: false,
        notes: "Dead hang start, curl knees to chest — no swinging, controlled lowering",
      },
      {
        id: "home-8",
        name: "Russian Twists",
        sets: 3,
        reps: "20",
        targetMuscle: "Obliques",
        trackWeight: true,
        repLabel: "Each side",
        notes: "Feet off floor, hold plate to chest — rotate fully side to side",
      },
      {
        id: "home-9",
        name: "Hollow Body Hold",
        sets: 3,
        reps: "30-45",
        targetMuscle: "Abs",
        trackWeight: false,
        repLabel: "Sec",
        notes: "Lower back pressed into floor, arms overhead — if hips rise, tuck knees",
      },
    ],
  },
  {
    id: "home-wrist",
    name: "Wrist & Forearm",
    icon: Home,
    day: "home",
    focus: "Forearms",
    color: "hsl(142 65% 48%)",
    exercises: [
      {
        id: "home-5",
        name: "Wrist Roller",
        sets: 3,
        reps: "3-5",
        targetMuscle: "Forearms",
        trackWeight: true,
        repLabel: "Lengths",
        notes: "Roll up and down counts as 1 — control the descent",
      },
      {
        id: "home-6",
        name: "Rice Bucket",
        sets: 3,
        reps: "60",
        targetMuscle: "Forearms",
        trackWeight: false,
        repLabel: "Sec",
        notes: "Finger extensions, fist clenches, rotations — 60s per set",
      },
    ],
  },
];
