UPDATE workout_sets SET exercise_name = CASE exercise_id
  WHEN 'acc-abs1-added-1777356256022-handles' THEN 'Cable Crunches'
  WHEN 'acc-abs1-handles' THEN 'Cable Crunches'
  WHEN 'acc-grip1' THEN 'Pinch Grip Plate Holds'
  WHEN 'acc-grip1-2h' THEN 'Pinch Grip Plate Holds'
  WHEN 'acc-grip2' THEN 'Farmer'
  WHEN 'acc-wrist1' THEN 'Wrist Curls'
  WHEN 'acc-wrist2' THEN 'Reverse Wrist Curls'
  WHEN 'lib-40' THEN 'Oblique Leg Raise'
  WHEN 'lib-44' THEN 'Reverse Curl'
  WHEN 'lib-db-Hack_Squat' THEN 'Hack Squat'
  WHEN 'pl1-no-attachment' THEN 'Seated Row Machine'
  WHEN 'pl3-lat-bar' THEN 'Lat Pull Down - Pronated Grip'
  WHEN 'pl3-no-attachment' THEN 'Lat Pull Down - Pronated Grip'
  WHEN 'pl4-heavy-rope' THEN 'Face Pulls'
  WHEN 'pu5-handles' THEN 'X-Over Cable Tricep Extensions'
  WHEN 'pu5-no-attachment' THEN 'X-Over Cable Tricep Extensions'
  WHEN 'pu6-cuff' THEN 'Single Arm Overhead Cable Tricep Extensions'
  WHEN 'pu6-handles' THEN 'Single Arm Overhead Cable Tricep Extensions'
  WHEN 'up1-mag-grip' THEN 'Seated Cable Row'
  WHEN 'up2-cuff-lat-bar' THEN 'Lat Pull Down'
  WHEN 'up2-handles' THEN 'Lat Pull Down'
  WHEN 'up2-mag-grip' THEN 'Lat Pull Down'
  WHEN 'up4-handles' THEN 'Cable Flies To Thighs'
  WHEN 'up8-heavy-v-bar' THEN 'Tricep Pushdown'
END
WHERE exercise_id = exercise_name AND exercise_id IN (
  'acc-abs1-added-1777356256022-handles','acc-abs1-handles','acc-grip1','acc-grip1-2h','acc-grip2','acc-wrist1','acc-wrist2','lib-40','lib-44','lib-db-Hack_Squat','pl1-no-attachment','pl3-lat-bar','pl3-no-attachment','pl4-heavy-rope','pu5-handles','pu5-no-attachment','pu6-cuff','pu6-handles','up1-mag-grip','up2-cuff-lat-bar','up2-handles','up2-mag-grip','up4-handles','up8-heavy-v-bar'
);